name: ci
on: [push, pull_request]
jobs:
  test-build:
    strategy:
      matrix:
        go-version: [1.15.x, 1.14.x, 1.13.x, 1.12.x, 1.11.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
        goos: ["linux", "darwin", "windows"]
        goarch: ["amd64"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Test
      run: go test -race -v ./...
    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: go build
