name: ci
on: [push, pull_request]
jobs:
  test-build:
    strategy:
      matrix:
        go-version: [1.15.x, 1.14.x, 1.13.x, 1.12.x, 1.11.x, 1.10.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Test
      run: if [ ${{ matrix.platform }} == "1.10.x" ]]; then export GOPATH=.; done; go test -race -v
    - name: Build
      run: |
        export GOOS=linux GOARCH=amd64
        echo "Building for $GOOS $GOARCH..."; go build
        export GOOS=darwin GOARCH=amd64
        echo "Building for $GOOS $GOARCH..."; go build
        export GOOS=windows GOARCH=amd64
        echo "Building for $GOOS $GOARCH..."; go build
        echo "Done"
